name: Mirror to SSO-API-Documentation

on:
  push:
    branches:
      - master  # Altere para 'main' se sua branch padrão for 'main'

jobs:
  mirror-sso:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_SSO }}

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Strip workflows before pushing
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          rm -rf .github/workflows
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Remove workflows for SSO mirror"
          fi

      - name: Add or update mirror remote (sem --mirror)
        run: |
          if git remote get-url mirror-sso >/dev/null 2>&1; then
            git remote set-url mirror-sso https://x-access-token:${GH_TOKEN}@github.com/739117_WYND/SSO-API-Documentation.git
          else
            git remote add mirror-sso https://x-access-token:${GH_TOKEN}@github.com/739117_WYND/SSO-API-Documentation.git
          fi

      - name: Push branch and tags to mirror
        run: |
          git push mirror-sso master --force
          git push mirror-sso --tags
