name: Mirror to SSO-API-Documentation

on:
  push:
    branches:
      - master    # ou sua branch padrão

jobs:
  mirror-sso:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_SSO }}

    steps:
      # 1) Checkout completo sem credential helper
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      # 2) Remove workflows para não ativar Actions no destino
      - name: Strip workflows before pushing
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          rm -rf .github/workflows
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Remove workflows for SSO mirror"
          fi

      # 3) Adiciona o remote com o token embutido
      - name: Add mirror remote
        run: |
          git remote add mirror-sso \
            https://x-access-token:${GH_TOKEN}@github.com/739117_WYND/SSO-API-Documentation.git

      # 4) Push forçado da branch master e de todas as tags
      - name: Push to SSO-API-Documentation
        run: |
          git push mirror-sso HEAD:master --force
          git push mirror-sso --tags
